"""empty message

Revision ID: fe5f65d83949
Revises: 
Create Date: 2024-09-27 16:20:34.018127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5f65d83949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('computers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=10), nullable=False),
    sa.Column('suit', sa.String(length=10), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=True),
    sa.Column('computer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alias_id'], ['aliases.id'], ),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.JSON(), nullable=False),
    sa.Column('table_card', sa.JSON(), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('winner', sa.String(length=100), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=True),
    sa.Column('computer_id', sa.Integer(), nullable=True),
    sa.Column('computer_hand', sa.JSON(), nullable=True),
    sa.Column('player_hand', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alias_id'], ['aliases.id'], ),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('cards')
    op.drop_table('computers')
    op.drop_table('aliases')
    # ### end Alembic commands ###
